// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKu18QfXcTHZxuwpVWNo21eLxnxjf5mpw',
    appId: '1:468968262370:web:afb8ab7038e592913f2cbb',
    messagingSenderId: '468968262370',
    projectId: 'airbnb-clone-46e81',
    authDomain: 'airbnb-clone-46e81.firebaseapp.com',
    storageBucket: 'airbnb-clone-46e81.firebasestorage.app',
    measurementId: 'G-4RR160DWQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmBXwfzCSE-0oQVCep62p6GFRLHfEdgw',
    appId: '1:468968262370:android:75a7f88e97dce2923f2cbb',
    messagingSenderId: '468968262370',
    projectId: 'airbnb-clone-46e81',
    storageBucket: 'airbnb-clone-46e81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pesewtQ3y4CZxQGxoLmJ1ssQZb5ljdc',
    appId: '1:468968262370:ios:edcffd4d28477fa73f2cbb',
    messagingSenderId: '468968262370',
    projectId: 'airbnb-clone-46e81',
    storageBucket: 'airbnb-clone-46e81.firebasestorage.app',
    iosBundleId: 'com.example.airBnbClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pesewtQ3y4CZxQGxoLmJ1ssQZb5ljdc',
    appId: '1:468968262370:ios:edcffd4d28477fa73f2cbb',
    messagingSenderId: '468968262370',
    projectId: 'airbnb-clone-46e81',
    storageBucket: 'airbnb-clone-46e81.firebasestorage.app',
    iosBundleId: 'com.example.airBnbClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKu18QfXcTHZxuwpVWNo21eLxnxjf5mpw',
    appId: '1:468968262370:web:862fda8bdddf3bfd3f2cbb',
    messagingSenderId: '468968262370',
    projectId: 'airbnb-clone-46e81',
    authDomain: 'airbnb-clone-46e81.firebaseapp.com',
    storageBucket: 'airbnb-clone-46e81.firebasestorage.app',
    measurementId: 'G-N54S312CJR',
  );

}